CREATE DATABASE ECOMMERCE
GO

USE ECOMMERCE
GO

CREATE TABLE CLIENTE(
	ID INT PRIMARY KEY IDENTITY,
	NOME VARCHAR(50) NOT NULL,
	DATANASC DATETIME NOT NULL,
	CPF VARCHAR(20) NOT NULL,	
	TELEFONE CHAR(20) NOT NULL,	
	EMAIL VARCHAR(50) NOT NULL,
	SENHA VARCHAR(20) NOT NULL
)
GO

BEGIN TRANSACTION
INSERT INTO CLIENTE VALUES('JAMILE','1995-06-22','099.016.041-61','99134-3899','JAMJAM@GMAIL.COM','123456SJ$$')
INSERT INTO CLIENTE VALUES('RODRIGO','2002-02-13','123.011.432-66','99935-0890','DIGODIGO@GMAIL.COM','87845454SS$')
INSERT INTO CLIENTE VALUES('PAMELA','1987-05-10','155.022.99-36','98875-0369','PAMPAM@GMAIL.COM','878784541XX&')
COMMIT
GO

CREATE TABLE ENDERECO(
	ID INT PRIMARY KEY IDENTITY,
	RUA VARCHAR(50) NOT NULL,
	BAIRRO VARCHAR(30) NOT NULL,
	NUMERO VARCHAR(10) NOT NULL,
	CEP VARCHAR(15) NOT NULL,
	COMPLEMENTO VARCHAR(50),
	PONTOREF VARCHAR(100),
	CIDADE VARCHAR(30) NOT NULL,
	ESTADO CHAR(2) NOT NULL,
	PAIS VARCHAR(20) NOT NULL,	
	ID_CLIENTE INT
)
GO

BEGIN TRANSACTION
INSERT INTO ENDERECO VALUES('ALDEBIADES','RIBEIRA','54','40420-021','1 ANDAR','AO LADO DA PREFEITURA','SALVADOR','BA','BRASIL',1)
INSERT INTO ENDERECO VALUES('JORGE LEAO','MASSARANDUBA','99','13221-000','TERREO','PERTO DA PADARIA','FEIRA DE SANTANA','BA','BRASIL',2)
INSERT INTO ENDERECO VALUES('AGUAS CRISTALINAS','PITUBA','33','44433-022','ULTIMO ANDAR','AZULEJO ROSA','RIO DE JANEIRO','RJ','BRASIL',3)
COMMIT
GO

ALTER TABLE ENDERECO
ADD CONSTRAINT FK_ENDERECO_CLIENTE
FOREIGN KEY(ID_CLIENTE)
REFERENCES CLIENTE(ID)
GO

CREATE TABLE PRODUTO(
	ID INT PRIMARY KEY IDENTITY,
	NOME VARCHAR(50) NOT NULL,
	PRECO FLOAT NOT NULL
)
GO

BEGIN TRANSACTION
INSERT INTO PRODUTO VALUES('CIMENTO',32.50)
INSERT INTO PRODUTO VALUES('ARGAMASSA',50.00)
INSERT INTO PRODUTO VALUES('VERGALHAO',60.00)
INSERT INTO PRODUTO VALUES('TUBO',25.00)
INSERT INTO PRODUTO VALUES('TRELICA',66.00)
INSERT INTO PRODUTO VALUES('IMPERMEABILIZANTE',170)
INSERT INTO PRODUTO VALUES('MADEIRA',80)
INSERT INTO PRODUTO VALUES('CAL',15)
INSERT INTO PRODUTO VALUES('ACO',10)
INSERT INTO PRODUTO VALUES('GESSO',20)
INSERT INTO PRODUTO VALUES('TINTA',200)
INSERT INTO PRODUTO VALUES('PISO',82)
COMMIT
GO

CREATE TABLE PEDIDO(
	ID INT PRIMARY KEY IDENTITY,
	DATAPEDIDO DATETIME NOT NULL,
	ID_CLIENTE INT NOT NULL
)
GO

BEGIN TRANSACTION
INSERT INTO PEDIDO VALUES('2022-09-01',1)
INSERT INTO PEDIDO VALUES('2022-09-01',1)
INSERT INTO PEDIDO VALUES('2022-09-01',1)
COMMIT
GO

ALTER TABLE PEDIDO
ADD CONSTRAINT FK_PEDIDO_CLIENTE
FOREIGN KEY(ID_CLIENTE)
REFERENCES CLIENTE(ID)
GO

CREATE TABLE PEDIDO_PRODUTO(
	ID INT PRIMARY KEY IDENTITY,
	ID_PEDIDO INT NOT NULL,
	ID_PRODUTO INT NOT NULL,
	QUANTIDADE INT NOT NULL
)
GO

ALTER TABLE PEDIDO_PRODUTO
ADD CONSTRAINT FK_PEDIDO
FOREIGN KEY(ID_PEDIDO)
REFERENCES PEDIDO(ID)
GO

ALTER TABLE PEDIDO_PRODUTO
ADD CONSTRAINT FK_PRODUTO
FOREIGN KEY(ID_PRODUTO)
REFERENCES PRODUTO(ID)
GO

BEGIN TRANSACTION
INSERT INTO PEDIDO_PRODUTO VALUES(1,1,5)
INSERT INTO PEDIDO_PRODUTO VALUES(1,2,10)
INSERT INTO PEDIDO_PRODUTO VALUES(1,3,15)
INSERT INTO PEDIDO_PRODUTO VALUES(2,1,11)
INSERT INTO PEDIDO_PRODUTO VALUES(2,5,4)
INSERT INTO PEDIDO_PRODUTO VALUES(2,3,8)
INSERT INTO PEDIDO_PRODUTO VALUES(3,4,7)
COMMIT
GO