CREATE DATABASE ECOMMERCE
GO

USE ECOMMERCE
GO

CREATE TABLE CLIENTES(
	ID INT PRIMARY KEY IDENTITY,
	NOME VARCHAR(50) NOT NULL,
	DATANASC DATETIME NOT NULL,
	CPF VARCHAR(20) NOT NULL,	
	TELEFONE CHAR(20) NOT NULL,	
	EMAIL VARCHAR(50) NOT NULL,
	SENHA VARCHAR(20) NOT NULL,
	ID_ENDERECO INT
)
GO

ALTER TABLE CLIENTES
ADD CONSTRAINT FK_CLIENTES_ENDERECOS
FOREIGN KEY(ID_ENDERECO)
REFERENCES ENDERECOS(ID)
GO

BEGIN TRANSACTION
INSERT INTO CLIENTES VALUES('JAMILE','1995-06-22','099.016.041-61','99134-3899','JAMJAM@GMAIL.COM','123456SJ$$',1)
INSERT INTO CLIENTES VALUES('RODRIGO','2002-02-13','123.011.432-66','99935-0890','DIGODIGO@GMAIL.COM','87845454SS$',2)
INSERT INTO CLIENTES VALUES('PAMELA','1987-05-10','155.022.99-36','98875-0369','PAMPAM@GMAIL.COM','878784541XX&',3)
COMMIT
GO

CREATE TABLE ENDERECOS(
	ID INT PRIMARY KEY IDENTITY,
	RUA VARCHAR(50) NOT NULL,
	BAIRRO VARCHAR(30) NOT NULL,
	NUMERO VARCHAR(10) NOT NULL,
	CEP VARCHAR(15) NOT NULL,
	COMPLEMENTO VARCHAR(50),
	PONTOREF VARCHAR(100),
	CIDADE VARCHAR(50) NOT NULL,
	ESTADO VARCHAR(30) NOT NULL,
	PAIS VARCHAR(50) NOT NULL
)
GO

BEGIN TRANSACTION
INSERT INTO ENDERECOS VALUES('ALDEBIADES','RIBEIRA','54','40420-021','1 ANDAR','AO LADO DA PREFEITURA','SALVADOR','BA','BRASIL',1)
INSERT INTO ENDERECOS VALUES('JORGE LEAO','MASSARANDUBA','99','13221-000','TERREO','PERTO DA PADARIA','FEIRA DE SANTANA','BA','BRASIL',2)
INSERT INTO ENDERECOS VALUES('AGUAS CRISTALINAS','PITUBA','33','44433-022','ULTIMO ANDAR','AZULEJO ROSA','RIO DE JANEIRO','RJ','BRASIL',3)
COMMIT
GO

CREATE TABLE PRODUTOS(
	ID INT PRIMARY KEY IDENTITY,
	NOME VARCHAR(50) NOT NULL,
	PRECO FLOAT NOT NULL
)
GO

BEGIN TRANSACTION
INSERT INTO PRODUTOS VALUES('CIMENTO',32.50)
INSERT INTO PRODUTOS VALUES('ARGAMASSA',50.00)
INSERT INTO PRODUTOS VALUES('VERGALHAO',60.00)
INSERT INTO PRODUTOS VALUES('TUBO',25.00)
INSERT INTO PRODUTOS VALUES('TRELICA',66.00)
INSERT INTO PRODUTOS VALUES('IMPERMEABILIZANTE',170)
INSERT INTO PRODUTOS VALUES('MADEIRA',80)
INSERT INTO PRODUTOS VALUES('CAL',15)
INSERT INTO PRODUTOS VALUES('ACO',10)
INSERT INTO PRODUTOS VALUES('GESSO',20)
INSERT INTO PRODUTOS VALUES('TINTA',200)
INSERT INTO PRODUTOS VALUES('PISO',82)
COMMIT
GO

CREATE TABLE PEDIDOS(
	ID INT PRIMARY KEY IDENTITY,
	DATAPEDIDO DATETIME NOT NULL,
	ID_CLIENTE INT NOT NULL
)
GO

BEGIN TRANSACTION
INSERT INTO PEDIDOS VALUES('2022-09-01',1)
INSERT INTO PEDIDOS VALUES('2022-09-01',1)
INSERT INTO PEDIDOS VALUES('2022-09-01',1)
COMMIT
GO

ALTER TABLE PEDIDOS
ADD CONSTRAINT FK_PEDIDOS_CLIENTES
FOREIGN KEY(ID_CLIENTE)
REFERENCES CLIENTES(ID)
GO

CREATE TABLE PEDIDOS_PRODUTOS(
	ID INT PRIMARY KEY IDENTITY,
	ID_PEDIDO INT NOT NULL,
	ID_PRODUTO INT NOT NULL,
	QUANTIDADE INT NOT NULL
)
GO

ALTER TABLE PEDIDOS_PRODUTOS
ADD CONSTRAINT FK_PEDIDOS
FOREIGN KEY(ID_PEDIDO)
REFERENCES PEDIDOS(ID)
GO

ALTER TABLE PEDIDOS_PRODUTOS
ADD CONSTRAINT FK_PRODUTOS
FOREIGN KEY(ID_PRODUTO)
REFERENCES PRODUTOS(ID)
GO

BEGIN TRANSACTION
INSERT INTO PEDIDOS_PRODUTOS VALUES(1,1,5)
INSERT INTO PEDIDOS_PRODUTOS VALUES(1,2,10)
INSERT INTO PEDIDOS_PRODUTOS VALUES(1,3,15)
INSERT INTO PEDIDOS_PRODUTOS VALUES(2,1,11)
INSERT INTO PEDIDOS_PRODUTOS VALUES(2,5,4)
INSERT INTO PEDIDOS_PRODUTOS VALUES(2,3,8)
INSERT INTO PEDIDOS_PRODUTOS VALUES(3,4,7)
COMMIT
GO